[package]
name = "lcd"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0"
hd44780-driver = "0.4"

stm32l4xx-hal = { version = "0.7", features = ["stm32l476", "rt"] }
